### ISSUE TITLE
API Authentication through Tokens is broken

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#2306]
Requesting an API resource with an `X-Auth-Token` header returns an `Internal Server Error 500`.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2306/create?referer=github" target="_blank">Log Time</a>

**Comment by normanrz** [comment]
```
play.api.UnexpectedException: Unexpected exception[AuthenticatorUpdateException: [Silhouette][bearer-token-authenticator] Could not update authenticator: BearerTokenAuthenticator([...],LoginInfo(credentials,tomh@scm.io),2018-01-18T13:34:36.520Z,2081-01-07T13:28:29.099Z,Some(1987200000 seconds))]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: com.mohiva.play.silhouette.api.exceptions.AuthenticatorUpdateException: [Silhouette][bearer-token-authenticator] Could not update authenticator: BearerTokenAuthenticator([...],LoginInfo(credentials,tomh@scm.io),2018-01-18T13:34:36.520Z,2081-01-07T13:28:29.099Z,Some(1987200000 seconds))
	at com.mohiva.play.silhouette.impl.authenticators.BearerTokenAuthenticatorService$$anonfun$update$1.applyOrElse(BearerTokenAuthenticator.scala:190) ~[com.mohiva.play-silhouette_2.11-3.0.5.jar:3.0.5]
	at com.mohiva.play.silhouette.impl.authenticators.BearerTokenAuthenticatorService$$anonfun$update$1.applyOrElse(BearerTokenAuthenticator.scala:189) ~[com.mohiva.play-silhouette_2.11-3.0.5.jar:3.0.5]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: java.lang.Exception: Attempted to open a Box incorrectly. Please use openOrThrowException.
	at net.liftweb.common.Box.get(Box.scala:279) ~[net.liftweb.lift-common_2.10-3.0-M1.jar:3.0-M1]
	at oxalis.security.BearerTokenAuthenticatorDAO$$anonfun$update$1.apply(BearerTokenAuthenticatorDAO.scala:42) ~[oxalis.oxalis-2.0.2-sans-externalized.jar:na]
	at oxalis.security.BearerTokenAuthenticatorDAO$$anonfun$update$1.apply(BearerTokenAuthenticatorDAO.scala:42) ~[oxalis.oxalis-2.0.2-sans-externalized.jar:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.8.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [com.typesafe.akka.akka-actor_2.11-2.4.1.jar:na]
```

**Comment by rschwanhold** [comment]
Do you know on which route this happend? In the error it looks like it the update function in BearerTokenAuthenticator failed (caused by `_.get`)

**Comment by hotzenklotz** [comment]
@rschwanhold I am not sure anymore. I think something like`/api/users`or `/api/projects`.
