### ISSUE TITLE
ArrayIndexOutOfBoundsException in histogram call for uint16 layer

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4405]
Let’s figure out if this is an error in the dataset, in wkw or in the webknossos backend

```
backend: ! @7efb7ah3e - Internal server error, for (GET) [/data/datasets/sample_organization/data_types/layers/color_uint16/histogram?token=rxBkERKXmWLU6iMAwNrNwg] ->
backend:  
backend: play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ArrayIndexOutOfBoundsException: null]]
backend: 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:351)
backend: 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
backend: 	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:448)
backend: 	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:446)
backend: 	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
backend: 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
backend: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
backend: 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
backend: 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
backend: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
backend: Caused by: java.lang.ArrayIndexOutOfBoundsException: null
backend: 	at com.scalableminds.webknossos.datastore.services.BinaryDataService.$anonfun$cutOutCuboid$4(BinaryDataService.scala:135)
backend: 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:155)
backend: 	at com.scalableminds.webknossos.datastore.services.BinaryDataService.$anonfun$cutOutCuboid$3(BinaryDataService.scala:121)
backend: 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:155)
backend: 	at com.scalableminds.webknossos.datastore.services.BinaryDataService.$anonfun$cutOutCuboid$2(BinaryDataService.scala:119)
backend: 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:155)
backend: 	at com.scalableminds.webknossos.datastore.services.BinaryDataService.$anonfun$cutOutCuboid$1(BinaryDataService.scala:118)
backend: 	at com.scalableminds.webknossos.datastore.services.BinaryDataService.$anonfun$cutOutCuboid$1$adapted(BinaryDataService.scala:97)
backend: 	at scala.collection.immutable.List.foreach(List.scala:388)
backend: 	at com.scalableminds.webknossos.datastore.services.BinaryDataService.cutOutCuboid(BinaryDataService.scala:97) 
```

**Comment by MichaelBuessemeyer** [comment]
the error that is shown in frontend toast: 
```
Execution exception

[ArrayIndexOutOfBoundsException: null]
In /home/michael/Desktop/ScalableMinds/webknossos/webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala:135

131
132          val resultOffset = (rx + ry * resultVolume.x + rz * resultVolume.x * resultVolume.y) * bytesPerElement
133          if (voxelDimensions.x == 1) {
134            // bulk copy a row of voxels
135            System.arraycopy(data, dataOffset, result, resultOffset, (xMax - x) * bytesPerElement)
136          } else {
137            // copy single voxel
138            System.arraycopy(data, dataOffset, result, resultOffset, bytesPerElement)
139          }

```

**Comment by MichaelBuessemeyer** [comment]
![image](https://user-images.githubusercontent.com/39529669/72338949-c3d20680-36c5-11ea-882a-d9830d6eae6e.png)

**Comment by MichaelBuessemeyer** [comment]
This is caused by the layer "color_uint16" of the test dataset `data_types`

**Comment by MichaelBuessemeyer** [comment]
![72338949-c3d20680-36c5-11ea-882a-d9830d6eae6e](https://user-images.githubusercontent.com/39529669/72344733-4234a580-36d2-11ea-8c49-e454305b3136.png)
