### ISSUE TITLE
Error when loading data when using OpenJDK 11

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4429]
When switching to OpenJDK 11, I get errors in loading data. Works with OpenJDK 8.
I took care to compile and run with the same version.
(Did not recompile webknossos-wrap though, not sure how this is handled. Using wkw 1.1.7, built 2019-02-04)

```
backend: ! @7el0770p0 - Internal server error, for (POST) [/data/datasets/sample_organization/<datasetname>/layers/color/data?token=<token>] ->
backend:  
backend: play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalArgumentException: Cannot locate field unsafe on class java.nio.DirectByteBufferR]]
backend: 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:351)
backend: 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
backend: 	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:448)
backend: 	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:446)
backend: 	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
backend: 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
backend: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
backend: 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
backend: 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
backend: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
backend: Caused by: java.lang.IllegalArgumentException: Cannot locate field unsafe on class java.nio.DirectByteBufferR
backend: 	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
backend: 	at org.apache.commons.lang3.reflect.FieldUtils.readField(FieldUtils.java:467)
backend: 	at com.scalableminds.webknossos.wrap.util.ExtendedTypes$ExtendedMappedByteBuffer.<init>(ExtendedTypes.scala:33)
backend: 	at com.scalableminds.webknossos.wrap.WKWFile.$anonfun$mapBuffers$1(WKWFile.scala:126)
backend: 	at com.scalableminds.webknossos.wrap.WKWFile.$anonfun$mapBuffers$1$adapted(WKWFile.scala:124)
backend: 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
backend: 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
backend: 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
backend: 	at scala.collection.mutable.ArrayOps$ofLong.foreach(ArrayOps.scala:254)
backend: 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
```

**Comment by fm3** [comment]
let’s check java version during datastore startup to at least provide a readable error message for this
