### ISSUE TITLE
unable to start, missing mail.subject 

### ISSUE THREAD

**Issue by paulobaptista** [scalableminds/webknossos#5059]
Running 20.12.0

2021-01-19 13:47:02,907 [INFO] Startup - Executing Startup
2021-01-19 13:47:04,071 [INFO] com.scalableminds.webknossos.tracingstore.tracings.FossilDBClient - Successfully tested FossilDB health at fossildb:7155. Reply: SERVING
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'mail.subject'
  at Startup.<init>(Startup.scala:25)
  at WebKnossosModule.configure(WebKnossosModule.scala:13) (via modules: com.google.inject.util.Modules$OverrideModule -> WebKnossosModule)
  while locating Startup

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:186)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:139)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'mail.subject'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at play.api.ConfigLoader$.$anonfun$stringLoader$2(Configuration.scala:1059)
	at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1054)
	at play.api.Configuration.get(Configuration.scala:230)
	at com.scalableminds.util.tools.ConfigReader.get(ConfigReader.scala:9)
	at com.scalableminds.util.tools.ConfigReader.get$(ConfigReader.scala:8)
	at utils.WkConf.get(WkConf.scala:9)
	at utils.WkConf$Mail$Subject$.<init>(WkConf.scala:47)
	at utils.WkConf$Mail$.Subject$lzycompute$1(WkConf.scala:46)
	at utils.WkConf$Mail$.Subject(WkConf.scala:46)
	at Startup.startActors(Startup.scala:103)
	at Startup.<init>(Startup.scala:36)
	at Startup$$FastClassByGuice$$f223da5d.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	... 9 more

**Comment by fm3** [comment]
Hello and thanks for your report!

This looks like something went wrong while updating to a newer webKnossos version. The configuration setting `mail.subject.prefix` was removed already in release 20.05. I assume the error shows up because an updated default config file is read, but with older webKnossos code.

Did this show up after upgrading to a newer version? If so, how exactly are you launching webKnossos? Are you using docker?

**Comment by paulobaptista** [comment]
Hello @fm3 thanks for the suggestion.  I reviewed our setup and the wrong image was used to start up.  The system is back online. We had an issue with our startup script.
