### ISSUE TITLE
Some Isosurface Requests fail

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5238]
## Context
On so far a single dataset some segments reproducibly create ArrayIndexOutOfBoundsExceptions in isosurface requests.

## Expected Behavior
Isosurface should be rendered

## Current Behavior
Error 400, frontend says retrying, but fails again.

## Steps to Reproduce the bug
See slack thread https://scm.slack.com/archives/C5AKLAV0B/p1614870158034900

**Comment by fm3** [comment]
Finally got a stack trace (after the server runs a while, only `null` is printed instead of the number and the stack trace). Maybe the cumsum cache breaks.

```
java.lang.ArrayIndexOutOfBoundsException: 299494
backend: 	at com.scalableminds.webknossos.datastore.storage.BoundingBoxCache.$anonfun$withCache$3(AgglomerateFileCache.scala:154)
backend: 	at com.scalableminds.webknossos.datastore.storage.BoundingBoxCache.$anonfun$withCache$3$adapted(AgglomerateFileCache.scala:154)
backend: 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
backend: 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
backend: 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
backend: 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
backend: 	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
backend: 	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
backend: 	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
backend: 	at com.scalableminds.webknossos.datastore.storage.BoundingBoxCache.withCache(AgglomerateFileCache.scala:154)
```
