### ISSUE TITLE
Volume data download sometimes contains truncated data.zip

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5684]
Downloaded a volume annotation. It worked via the allDataBlocking route directly, but when using the wk-side download, the inner zip seems to be incomplete. I expect there is some race condition when waiting for the data.zip. Note that I cannot say with certainty whether the problem is on wk side or tracingstore side.

**Comment by fm3** [comment]
Unfortunately I cannot reproduce the issue anymore, neither in production nor test setup :/

**Comment by jstriebel** [comment]
There seems to be the same or a similar problem with the annotation mentioned in https://github.com/scalableminds/webknossos-libs/issues/534, the annotation download contains a corrupted data.zip, and during the download the following logs occur:

```
2021-12-20 11:22:20,427 [ERROR] akka.dispatch.Dispatcher - Timeout on waiting for new data
java.io.IOException: Timeout on waiting for new data
at akka.stream.impl.io.InputStreamAdapter.$anonfun$read$5(InputStreamSinkStage.scala:171)
at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:131)
at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:156)
at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:145)
at play.api.libs.iteratee.Enumerator$.$anonfun$fromStream$2(Enumerator.scala:563)
at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
```

When using the allDataBlocking route the download aborted ("network error") after roughly 30s, but nothing suspicious in the logs. The downloaded length varies across retries.

Internal details can be found [in this thread](https://scm.slack.com/archives/C5AKLAV0B/p1639996444001400).

**Comment by fm3** [comment]
Looks like this is indeed still open even after fixing the allDataBlocking route in #5927  – another user reported an instance of this bug, compare https://forum.image.sc/t/volume-annotation-upload-timeout/62309/5

**Comment by fm3** [comment]
We received no more reports of this since https://github.com/scalableminds/webknossos/pull/6009 was deployed two months ago – let’s reopen if it occurs again
