### ISSUE TITLE
webknossos can't send emails

### ISSUE THREAD

**Issue by thopp-tudelft** [scalableminds/webknossos#6688]
## Context

Whenever the instance of the webknossos docker image version 22.12.0 tries to send an email the following message is placed in the log:
```
2022-12-09 11:12:25,503 [ERROR] akka.actor.OneForOneStrategy - Cannot find valid hostname for mail session
org.apache.commons.mail.EmailException: Cannot find valid hostname for mail session
	at org.apache.commons.mail.Email.getMailSession(Email.java:647)
	at oxalis.mail.Mailer.oxalis$mail$Mailer$$send(Mailer.scala:59)
	at oxalis.mail.Mailer$$anonfun$receive$1.applyOrElse(Mailer.scala:31)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at oxalis.mail.Mailer.aroundReceive(Mailer.scala:27)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
```
The documentation has no information about specific settings that need to be configured to have this work, nor is the error message very insightful.

## Expected Behavior

An email should be sent. Or a message that says there is a configuration error should appear in the logs instead of an exception.

## Current Behavior

Nothing, the interface gives a message to the user that an email will be sent but it never is.

## Steps to Reproduce the bug
1. Start the docker image with the default parameters from the documentation [here](https://docs.webknossos.org/webknossos/installation.html) with VIRTUAL_HOST set and the datastores etc...
2. Set it up etc...
3. Try to register an account
4. An email should be sent here to the admin but it isn't

## Your Environment for bug

- Browser name and version: all browsers
- Operating System and version: Ubuntu 20.04
- Version of WebKnossos (Release or Commit): 22.12.0

**Comment by thopp-tudelft** [comment]
Based on reading the configuration [here](https://github.com/scalableminds/webknossos/blob/7b095666c889fd7506081f9c7787c79629c43a22/conf/application.conf#L173) I have added the following parameters to the docker container command: `-Dmail.smtp.host=host.docker.internal -Dmail.smtp.port=25 -Dmail.smtp.tls=false -Dmail.smtp.auth=false`

This clearly does change something as it now shows an exception from the next line in Mailer.scala:
```
2022-12-09 13:50:38,172 [ERROR] akka.actor.OneForOneStrategy - From address required
org.apache.commons.mail.EmailException: From address required
	at org.apache.commons.mail.Email.buildMimeMessage(Email.java:1382)
	at org.apache.commons.mail.MultiPartEmail.buildMimeMessage(MultiPartEmail.java:253)
	at org.apache.commons.mail.HtmlEmail.buildMimeMessage(HtmlEmail.java:515)
	at org.apache.commons.mail.Email.send(Email.java:1495)
	at oxalis.mail.Mailer.oxalis$mail$Mailer$$send(Mailer.scala:62)
	at oxalis.mail.Mailer$$anonfun$receive$1.applyOrElse(Mailer.scala:31)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at oxalis.mail.Mailer.aroundReceive(Mailer.scala:27)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
```

The logs on the local smtp server do not report any attempt at a connection being made. I have verified the docker container can connect and send emails using smtp: `docker exec -it --user root webknossos_webknossos_1 /bin/bash -c "apt update && apt install netcat -y && echo -e 'EHLO $VIRTUAL_HOST\nMAIL FROM: <webknossos@$VIRTUAL_HOST>\nRCPT TO: $MY_EMAIL_ADDRESS\nDATA\nSubject: test from webknossos docker container\n\nThis is a test.\n.\nQUIT' | nc host.docker.internal 25"

Looking at where this traceback leads I find something concerning though, it seems like the mail.smtp.auth configuration option is never used? https://github.com/scalableminds/webknossos/blob/07099ce292b2b7caecbbe9736f9a91ab19797a11/app/oxalis/mail/Mailer.scala#L57
To me this seems like a simple fix by wrapping this line in `if (conf.smtpAuth) {}`, I'm not a scala programmer though.

**Comment by thopp-tudelft** [comment]
Trying with the version generated by circle ci on #6692 still gives the same error traceback as my previous comment:
```
2022-12-13 14:44:42,700 [ERROR] akka.actor.OneForOneStrategy - From address required
org.apache.commons.mail.EmailException: From address required
	at org.apache.commons.mail.Email.buildMimeMessage(Email.java:1382)
	at org.apache.commons.mail.MultiPartEmail.buildMimeMessage(MultiPartEmail.java:253)
	at org.apache.commons.mail.HtmlEmail.buildMimeMessage(HtmlEmail.java:515)
	at org.apache.commons.mail.Email.send(Email.java:1495)
	at oxalis.mail.Mailer.oxalis$mail$Mailer$$send(Mailer.scala:65)
	at oxalis.mail.Mailer$$anonfun$receive$1.applyOrElse(Mailer.scala:32)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at oxalis.mail.Mailer.aroundReceive(Mailer.scala:28)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
```

**Comment by fm3** [comment]
Thanks for your reply! I believe the exception you are getting is unrelated to the auth setting problem. From the error message, my guess is that the `from` email adress cannot be correctly set. I added another line in #6692 to add more readable error logging. Could it be that `mail.defaultSender` is set to something that could not be parsed as an email address in your test setup?

**Comment by thopp-tudelft** [comment]
I've set and unset the mail.defaultSender value before and it would still send error messages, I've looked at it again now and it does solve the problem, emails are sent now but the urls in the emails go to http://localhost:9000 instead of the domain name I have provided.

Does the mail.reply value do anything? I don't see it being used.

**Comment by fm3** [comment]
Good to hear! mail.reply is unused, I have removed it now in the PR.
The config value `http.uri` is used for the links in the emails.

**Comment by thopp-tudelft** [comment]
thanks!

So far though only leaving mail.defaultSender unset has my mails get sent, even setting it to the default value like this will not send any mails:
```
      - -Dmail.defaultSender="webKnossos <no-reply@webknossos.org>"
```
The added exception code from 6692 does not change the output, it stays `From address required`

**Comment by fm3** [comment]
Huh, not sure what is happening there. Maybe docker eats the quotation marks, so that the string containing spaces is not passed to java properly?

The new logging doesn’t change the exception but rather outputs a separatate logging line before. Maybe you missed it? Or something else is going on here :thinking:

**Comment by thopp-tudelft** [comment]
Ah, you're correct:
```
2022-12-13 15:35:34,953 [WARN] oxalis.mail.Mailer - Failed to set email address: org.apache.commons.mail.EmailException: javax.mail.internet.AddressException: Missing final '@domain' in string ``"webKnossos <no-reply@webknossos.org>"''
```
I've tried adding more quotes, escaping them, and escaping the escape characters, what I did not expect is that the quotes were implicitly added in docker-compose, changing my config to not have any quotes is what fixed it:
```
      - -Dmail.defaultSender=webKnossos <no-reply@webknossos.org>
```
like this it does work

**Comment by thopp-tudelft** [comment]
it's unfortunate these things are not properly documented though, perhaps adding mailing abilities with eg a docker container running postfix to https://github.com/scalableminds/webknossos/blob/master/tools/hosting/docker-compose.yml might be helpful

my setup uses postfix running on the host system however, these are the additions I've made to the docker-compose.yml:
```yml
services:
  webknossos:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - -Dhttp.uri=https://${PUBLIC_HOST}
      - -Dmail.smtp.host=host.docker.internal
      - -Dmail.smtp.port=25
      - -Dmail.smtp.tls=false
      - -Dmail.smtp.auth=false
      - -Dmail.defaultSender=webKnossos <no-reply@${PUBLIC_HOST}>
```
additionally I've had to add the subnet docker uses to postfix's main.cf:
```
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.16.0.0/12
```
